on:
    push
jobs:
    idle:
        runs-on: ubuntu-latest
        steps:
            -
                run: |
                    echo Idle Step
                    apt update
                    apt install figlet
