name: minimal

on:
    push
jobs:
    idle:
        name: LongName
        runs-on: ubuntu-latest
        steps:
            -
                name: prerequisites
                run: |
                    echo Idle Step
                    sudo apt update
                    sudo apt install figlet
            -
                name: usage
                run: |
                    figlet hello
